export const useProfileSchema = [
  {
    placeholder: 'Enter your full name',
    label: 'Your Name',
    name: 'fullName',
    type: 'text',
    valErrorMsg: 'Please enter your full name',
    errorMsg: 'Invalid name',
    required: true,
  },
  {
    placeholder: 'Enter your user name',
    label: 'User Name',
    name: 'userName',
    type: 'text',
    valErrorMsg: 'Please enter your user name',
    errorMsg: 'Invalid userName',
    required: true,
  },
  {
    placeholder: 'Enter your email',
    label: 'Email',
    name: 'email',
    type: 'text',
    valErrorMsg: 'Please enter your email',
    errorMsg: 'Invalid email',
    required: true,
  },
  {
    placeholder: 'Enter your password',
    label: 'Password',
    name: 'password',
    type: 'password',
    valErrorMsg: 'Please enter your password',
    errorMsg:
      'Password must be 8+ characters, with a mix of letters, numbers, and a special character',
    required: true,
  },
  {
    placeholder: 'Enter your date of birth',
    label: 'Date of Birth',
    name: 'dateOfBirth',
    type: 'date',
    valErrorMsg: 'Please enter your date of birth',
    errorMsg: 'Invalid date of birth',
    required: true,
  },
  {
    placeholder: 'Enter your present address',
    label: 'Present Address',
    name: 'presentAddress',
    type: 'text',
    valErrorMsg: 'Please enter your present address',
    errorMsg: 'Invalid present address',
    required: false,
  },
  {
    placeholder: 'Enter your permanent address',
    label: 'Permanent Address',
    name: 'permanentAddress',
    type: 'text',
    valErrorMsg: 'Please enter your permanent address',
    errorMsg: 'Invalid permanent address',
    required: true,
  },
  {
    placeholder: 'Enter your city',
    label: 'City',
    name: 'city',
    type: 'text',
    valErrorMsg: 'Please enter your city',
    errorMsg: 'Invalid city',
    required: true,
  },
  {
    placeholder: 'Enter your postal code',
    label: 'Postal Code',
    name: 'postalCode',
    type: 'text',
    valErrorMsg: 'Please enter your postal code',
    errorMsg: 'Invalid postal code',
    required: true,
  },
  {
    placeholder: 'Enter your country',
    label: 'Country',
    name: 'country',
    type: 'text',
    valErrorMsg: 'Please enter your country',
    errorMsg: 'Invalid country',
    required: true,
  },
];
