export const FETCH_CARD_DATA = 'FETCH_CARD_DATA';
export const FETCH_TRANSACTION_DATA = 'FETCH_TRANSACTION_DATA';
export const FETCH_WEEKLY_ACTIVITY = 'FETCH_WEEKLY_ACTIVITY';
export const FETCH_EXPENSE_STATISTICS = 'FETCH_EXPENSE_STATISTICS';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_BALANCE_HISTORY = 'FETCH_BALANCE_HISTORY';
